version: '3'

services:
  annotatechange:
    image: gjjvdburg/annotatechange:latest
    build: .
    env_file: .env
    labels:
      - "traefik.backend=annotatechange"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:timeseries.disim.univaq.it"
      - "traefik.port=7831"
    ports:
      - "80:7831"
    networks:
      - internal
      - web
    depends_on:
      - db
    volumes:
      - ./persist/instance:/home/annotatechange/instance

  db:
    image: mysql
    env_file: .env
    volumes:
      - ./persist/mysql:/var/lib/mysql
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    cap_add:
      - SYS_NICE # https://stackoverflow.com/q/55559386/

networks:
  web:
    external: true
  internal:
    external: false
